### ISSUE TITLE
Unable to connect to dedicated server

### ISSUE THREAD

**Issue by drakray** [Visnaa/GemstonePower#1]
```
Caused by: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:\u000F
	at net.minecraft.resources.ResourceLocation.m_245185_(ResourceLocation.java:236) ~[client-1.20.1-20230612.114412-srg.jar%23776!/:?]
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:38) ~[client-1.20.1-20230612.114412-srg.jar%23776!/:?]
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:42) ~[client-1.20.1-20230612.114412-srg.jar%23776!/:?]
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:46) ~[client-1.20.1-20230612.114412-srg.jar%23776!/:?]
	at net.minecraft.network.FriendlyByteBuf.m_130281_(FriendlyByteBuf.java:711) ~[client-1.20.1-20230612.114412-srg.jar%23776!/:?]
	at net.minecraftforge.common.extensions.IForgeFriendlyByteBuf.readRegistryId(IForgeFriendlyByteBuf.java:99) ~[forge-1.20.1-47.1.70-universal.jar%23781!/:?]
	at net.minecraftforge.fluids.FluidStack.readFromPacket(FluidStack.java:143) ~[forge-1.20.1-47.1.70-universal.jar%23781!/:?]
	at com.visnaa.gemstonepower.data.recipe.OreWasherRecipe$Serializer.fromNetwork(OreWasherRecipe.java:174) ~[gemstonepower-1.20.1-v0.2.8.jar%23610!/:0.2.8]
	at com.visnaa.gemstonepower.data.recipe.OreWasherRecipe$Serializer.m_8005_(OreWasherRecipe.java:140) ~[gemstonepower-1.20.1-v0.2.8.jar%23610!/:0.2.8]
	at net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.m_133647_(ClientboundUpdateRecipesPacket.java:45) ~[client-1.20.1-20230612.114412-srg.jar%23776!/:?]
	at net.minecraft.network.FriendlyByteBuf.m_236838_(FriendlyByteBuf.java:211) ~[client-1.20.1-20230612.114412-srg.jar%23776!/:?]
	at net.minecraft.network.FriendlyByteBuf.m_236845_(FriendlyByteBuf.java:227) ~[client-1.20.1-20230612.114412-srg.jar%23776!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.<init>(ClientboundUpdateRecipesPacket.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23776!/:?]
	at net.minecraft.network.ConnectionProtocol$PacketSet.m_178327_(ConnectionProtocol.java:459) ~[client-1.20.1-20230612.114412-srg.jar%23776!/:?]
	at net.minecraft.network.ConnectionProtocol.m_178321_(ConnectionProtocol.java:522) ~[client-1.20.1-20230612.114412-srg.jar%23776!/:?]
	at net.minecraft.network.PacketDecoder.decode(PacketDecoder.java:32) ~[client-1.20.1-20230612.114412-srg.jar%23776!/:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519) ~[netty-codec-4.1.82.Final.jar%23122!/:4.1.82.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458) ~[netty-codec-4.1.82.Final.jar%23122!/:4.1.82.Final]
	... 34 more
```

NeoForge 47.1.70
GemStone 0.2.8
Other Mods

Removing gemstone remove the error

**Comment by Visnaa** [comment]
Fixed in version beta 0.2.9
